import fcntl
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .. import config

LOCK_PATH = "/tmp/syslog-server-rsyslog.lock"


def generate_rsyslog_config(spaces: list) -> str:
    lines = [
        "# AUTO-GENERATED by syslog-server — DO NOT EDIT MANUALLY",
        f"# Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        'module(load="imudp")',
        "",
    ]

    enabled = [s for s in spaces if s.enabled]

    # Load imtcp if any space has TCP enabled
    if any(getattr(s, "tcp_enabled", False) for s in enabled):
        lines.insert(4, 'module(load="imtcp")')
        lines.insert(5, "")

    if not enabled:
        lines.append("# No enabled spaces — no inputs configured")
        return "\n".join(lines) + "\n"

    # One dynamic filename template per space
    for space in enabled:
        log_dir = f"{config.LOG_ROOT}/{space.port}/"
        lines += [
            f'template(name="tpl_{space.port}" type="list") {{',
            f'    constant(value="{log_dir}")',
            f'    property(name="fromhost-ip")',
            f'    constant(value=".log")',
            f"}}",
            "",
        ]

    # One ruleset per space (with optional IP filter)
    for space in enabled:
        allowed_ip = getattr(space, "allowed_ip", None)
        action_lines = [
            f'    action(',
            f'        type="omfile"',
            f'        dynaFile="tpl_{space.port}"',
            f'        dirCreateMode="0755"',
            f'        fileCreateMode="0640"',
            f'        fileOwner="syslog"',
            f'        fileGroup="adm"',
            f'    )',
        ]
        if getattr(space, "lan_mode", False):
            action_lines += [
                f'    action(',
                f'        type="omfile"',
                f'        file="{config.LOG_ROOT}/{space.port}/_all.log"',
                f'        fileCreateMode="0640"',
                f'        fileOwner="syslog"',
                f'        fileGroup="adm"',
                f'    )',
            ]
        if allowed_ip:
            lines += [
                f'ruleset(name="rs_{space.port}") {{',
                f'    if $fromhost-ip == "{allowed_ip}" then {{',
            ] + [f'    {l}' for l in action_lines] + [
                f'    }}',
                f'    stop',
                f"}}",
                "",
            ]
        else:
            lines += [f'ruleset(name="rs_{space.port}") {{'] + action_lines + [f"}}", ""]

    # Inputs: UDP always, TCP if enabled
    for space in enabled:
        lines.append(
            f'input(type="imudp" port="{space.port}" ruleset="rs_{space.port}")'
        )
        if getattr(space, "tcp_enabled", False):
            lines.append(
                f'input(type="imtcp" port="{space.port}" ruleset="rs_{space.port}")'
            )

    return "\n".join(lines) + "\n"


def _validate_config(conf_path: str) -> tuple[bool, str]:
    result = subprocess.run(
        ["rsyslogd", "-N1", "-f", conf_path],
        capture_output=True, text=True, timeout=10,
    )
    return result.returncode == 0, result.stderr


def _reload_rsyslog() -> tuple[bool, str]:
    # Full restart required to bind/unbind UDP/TCP sockets
    result = subprocess.run(
        ["systemctl", "restart", "rsyslog"],
        capture_output=True, text=True, timeout=20,
    )
    return result.returncode == 0, result.stderr


def apply_rsyslog_config(spaces: list) -> tuple[bool, str]:
    conf = config.RSYSLOG_CONF
    bak = config.RSYSLOG_CONF_BAK

    for space in spaces:
        if space.enabled:
            log_dir = Path(config.LOG_ROOT) / str(space.port)
            log_dir.mkdir(parents=True, exist_ok=True)
            try:
                os.chown(str(log_dir), _uid("syslog"), _gid("adm"))
            except (LookupError, PermissionError):
                pass

    new_config = generate_rsyslog_config(spaces)

    with open(LOCK_PATH, "w") as lock_file:
        fcntl.flock(lock_file, fcntl.LOCK_EX)
        try:
            if os.path.exists(conf):
                shutil.copy2(conf, bak)

            with open(conf, "w") as f:
                f.write(new_config)

            ok, err = _validate_config(conf)
            if not ok:
                if os.path.exists(bak):
                    shutil.copy2(bak, conf)
                return False, f"rsyslog config invalide: {err}"

            ok, err = _reload_rsyslog()
            if not ok:
                return False, f"rsyslog restart échoué: {err}"

            return True, "OK"
        finally:
            fcntl.flock(lock_file, fcntl.LOCK_UN)


def _uid(name: str) -> int:
    import pwd
    return pwd.getpwnam(name).pw_uid


def _gid(name: str) -> int:
    import grp
    return grp.getgrnam(name).gr_gid
